# Build Stage

FROM golang:1.19 AS api-build-env

WORKDIR /app

FROM node:18 AS ui-build-env

WORKDIR /src
ADD webui .
RUN yarn && \
    yarn build

# Run Stage

# When running the application using `docker run`, you can pass environment variables
# to override config values using `-e` syntax.

FROM alpine
WORKDIR /app

COPY mailwhale README.md version.txt LICENSE config.yml templates/ ./
COPY --from=ui-build-env /src/public ./webui/public

ENV MW_ENV=prod
ENV MW_WEB_LISTEN_V4=0.0.0.0:3000
ENV MW_STORE_PATH=/data/data.json.db

VOLUME /data

ENTRYPOINT ./mailwhale
